
return {
   FAILED =                     "org.freedesktop.DBus.Error.Failed",
   NO_MEMORY =                  "org.freedesktop.DBus.Error.NoMemory",
   SERVICE_UNKNOWN =            "org.freedesktop.DBus.Error.ServiceUnknown",
   NAME_HAS_NO_OWNER =          "org.freedesktop.DBus.Error.NameHasNoOwner",
   NO_REPLY =                   "org.freedesktop.DBus.Error.NoReply",
   IO_ERROR =                   "org.freedesktop.DBus.Error.IOError",
   BAD_ADDRESS =                "org.freedesktop.DBus.Error.BadAddress",
   NOT_SUPPORTED =              "org.freedesktop.DBus.Error.NotSupported",
   LIMITS_EXCEEDED =            "org.freedesktop.DBus.Error.LimitsExceeded",
   ACCESS_DENIED =              "org.freedesktop.DBus.Error.AccessDenied",
   AUTH_FAILED =                "org.freedesktop.DBus.Error.AuthFailed",
   NO_SERVER =                  "org.freedesktop.DBus.Error.NoServer",
   TIMEOUT =                    "org.freedesktop.DBus.Error.Timeout",
   NO_NETWORK =                 "org.freedesktop.DBus.Error.NoNetwork",
   ADDRESS_IN_USE =             "org.freedesktop.DBus.Error.AddressInUse",
   DISCONNECTED =               "org.freedesktop.DBus.Error.Disconnected",
   INVALID_ARGS =               "org.freedesktop.DBus.Error.InvalidArgs",
   FILE_NOT_FOUND =             "org.freedesktop.DBus.Error.FileNotFound",
   FILE_EXISTS =                "org.freedesktop.DBus.Error.FileExists",
   UNKNOWN_METHOD =             "org.freedesktop.DBus.Error.UnknownMethod",
   UNKNOWN_OBJECT =             "org.freedesktop.DBus.Error.UnknownObject",
   UNKNOWN_INTERFACE =          "org.freedesktop.DBus.Error.UnknownInterface",
   UNKNOWN_PROPERTY =           "org.freedesktop.DBus.Error.UnknownProperty",
   PROPERTY_READ_ONLY =         "org.freedesktop.DBus.Error.PropertyReadOnly",
   UNIX_PROCESS_ID_UNKNOWN =    "org.freedesktop.DBus.Error.UnixProcessIdUnknown",
   INVALID_SIGNATURE =          "org.freedesktop.DBus.Error.InvalidSignature",
   INCONSISTENT_MESSAGE =       "org.freedesktop.DBus.Error.InconsistentMessage",
   MATCH_RULE_NOT_FOUND =       "org.freedesktop.DBus.Error.MatchRuleNotFound",
   MATCH_RULE_INVALID =         "org.freedesktop.DBus.Error.MatchRuleInvalid",
   INTERACTIVE_AUTHORIZATION_REQUIRED = "org.freedesktop.DBus.Error.InteractiveAuthorizationRequired",
}
